# Site settings
title: Laura D. Melling
email: ldm@ldmelling.com
description: Website of Laura D. Melling
baseurl: ""

# Build settings
markdown: kramdown
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
gems:
  - jemoji
